#!/bin/bash

echo "⚙️  Running swiftlint"

if [ "$GITHUB_ACTIONS" = "true" ]; then
  echo "⚙️ Running in GitHub Actions, there is no need to validate swiftlint"
  exit
fi

if [[ "$(uname -m)" == arm64 ]]; then
    export PATH="/opt/homebrew/bin:$PATH"
fi

if which swiftlint > /dev/null; then
  swiftlint
else
  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
fi
