name: Auto approve

on: 
  pull_request_target:
    types: 
      - labeled
      - unlabeled
      - opened

jobs:
  auto-approve:
    name: Auto-approve
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'auto-approve') }}
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "LGTM!"

  dismiss-approvals:
    name: Auto-disapprove
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'auto-approve') }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Pull Request Reviews
        run: |
          REVIEWS=$(gh api repos/$REPOSITORY/pulls/$PR_NUMBER/reviews --jq '.[] | select(.state=="APPROVED") | .id')
          for REVIEW_ID in $REVIEWS; do
            gh api \
              -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: Bearer $GH_TOKEN" \
              repos/$REPOSITORY/pulls/$PR_NUMBER/reviews/$REVIEW_ID/dismissals \
              -f message='Please add the `auto-approve` label to keep github-actions' approve'
          done
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
