name: Auto approve

on: pull_request_target

jobs:
  detect:
    name: Verify checks
    runs-on: ubuntu-latest
    outputs:
      checked: ${{ steps.detects.outputs.checked }}
      unchecked: ${{ steps.detects.outputs.unchecked }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkbox Trigger
        id: detects
        uses: karlderkaefer/github-action-checkbox-trigger@v1
        with:
          github-token: ${{ github.token }}
          action: detect
      - name: list changes
        run: |
          echo "checked=${{ steps.detects.outputs.checked }}"
          echo "unchecked=${{ steps.detects.outputs.unchecked }}"

  auto-approve:
    name: Auto-approve
    runs-on: ubuntu-latest
    needs: detect
    permissions:
      pull-requests: write
    if: ${{ contains(needs.detect.outputs.checked, 'Auto approve') }}
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          review-message: "LGTM"

  dismiss-approvals:
    name: Auto-disapprove
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ !(contains(needs.detect.outputs.checked, 'Auto approve')) }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Pull Request Reviews
        run: |
          REVIEWS=$(gh api repos/$REPOSITORY/pulls/$PR_NUMBER/reviews --jq '.[] | select(.state=="APPROVED") | .id')
          for REVIEW_ID in $REVIEWS; do
            gh api \
              -X PUT \
              -H "Accept: application/vnd.github.v3+json" \
              repos/$REPOSITORY/pulls/$PR_NUMBER/reviews/$REVIEW_ID/dismissals \
              -f message='Dismissing approval via GitHub Actions'
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          REPOSITORY: ${{ github.repository }}
